import { Product } from '../types';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod-jordan-1-lost-and-found',
    handle: 'air-jordan-1-retro-high-og-chicago-lost-and-found',
    title: "Air Jordan 1 Retro High OG 'Chicago Lost & Found'",
    bodyHtml: '<p>Культова класика 1985 року у вінтажному переосмисленні з потрісканою натуральною шкірою, оригінальною формою носка та автентичною ретро-коробкою. Символ снікер-культури, який поєднує спадщину Майкла Джордана та вуличний стиль сучасності.</p><ul><li><strong>Матеріали:</strong> 100% преміальна натуральна шкіра, текстильна підкладка, зносостійка гумова підошва з амортизацією Nike Air.</li><li><strong>Комплектація:</strong> оригінальна вінтажна коробка, додаткові чорні та білі шнурки, стилізований вінтажний чек 1986 року.</li><li><strong>Автентичність:</strong> 100% оригінал, verified legit check.</li></ul>',
    vendor: 'Jordan',
    productType: 'Взуття / Кросівки',
    tags: ['Кросівки', 'Jordan', 'Хіт', 'Deadstock', 'Взуття', 'Unisex', 'New In'],
    price: 9800,
    compareAtPrice: 11500,
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'DZ5485-612',
    variants: [
      { id: 'v-jordan-41', title: 'EU 41 (26.0 cm)', price: 9800, compareAtPrice: 11500, sku: 'DZ5485-612-41' },
      { id: 'v-jordan-42', title: 'EU 42 (26.5 cm)', price: 9800, compareAtPrice: 11500, sku: 'DZ5485-612-42' },
      { id: 'v-jordan-425', title: 'EU 42.5 (27.0 cm)', price: 9800, compareAtPrice: 11500, sku: 'DZ5485-612-425' },
      { id: 'v-jordan-43', title: 'EU 43 (27.5 cm)', price: 9800, compareAtPrice: 11500, sku: 'DZ5485-612-43' },
      { id: 'v-jordan-44', title: 'EU 44 (28.0 cm)', price: 9800, compareAtPrice: 11500, sku: 'DZ5485-612-44' },
      { id: 'v-jordan-45', title: 'EU 45 (29.0 cm)', price: 9800, compareAtPrice: 11500, sku: 'DZ5485-612-45' },
    ],
  },
  {
    id: 'prod-stussy-basic-hoodie-black',
    handle: 'stussy-basic-logo-pullover-hoodie-black',
    title: "Stüssy Basic Applique Hoodie 'Black'",
    bodyHtml: '<p>Фірмове важке худі від каліфорнійського піонера streetwear-культури Stüssy. Вільний розслаблений силует (relaxed fit), спущена лінія плечей та культовий рукописний логотип Шона Стуссі на грудях і спині.</p><ul><li><strong>Склад:</strong> 80% щільна бавовна (Heavyweight Fleece 380 GSM), 20% поліестер.</li><li><strong>Деталі:</strong> глибокий подвійний капюшон, кишеня-кенгуру, еластичні манжети в рубчик.</li><li><strong>Посадка:</strong> Relaxed / Oversize.</li></ul>',
    vendor: 'Stüssy',
    productType: 'Одяг / Худі та світшоти',
    tags: ['Худі', 'Stüssy', 'Одяг', 'Oversize', 'Хіт', 'Чоловіче', 'Унісекс'],
    price: 5400,
    compareAtPrice: 6200,
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'STU-HOOD-BLK',
    variants: [
      { id: 'v-stu-s', title: 'S (Oversize)', price: 5400, compareAtPrice: 6200, sku: 'STU-HOOD-BLK-S' },
      { id: 'v-stu-m', title: 'M (Oversize)', price: 5400, compareAtPrice: 6200, sku: 'STU-HOOD-BLK-M' },
      { id: 'v-stu-l', title: 'L (Oversize)', price: 5400, compareAtPrice: 6200, sku: 'STU-HOOD-BLK-L' },
      { id: 'v-stu-xl', title: 'XL (Oversize)', price: 5400, compareAtPrice: 6200, sku: 'STU-HOOD-BLK-XL' },
    ],
  },
  {
    id: 'prod-newbalance-1906r-silver',
    handle: 'new-balance-1906r-silver-metallic-castlerock',
    title: "New Balance 1906R 'Silver Metallic / Cordura'",
    bodyHtml: '<p>Технологічний ретро-раннер початку 2000-х років, що став головним фаворитом снікерхедів у всьому світі. Поєднує металізовані накладки, дихаючу сітку та підошву N-ergy з амортизацією ABZORB для максимального комфорту під час щоденного носіння.</p><ul><li><strong>Технології:</strong> амортизація ABZORB SBS, підошва N-ergy, система фіксації шнурівки N-Lock.</li><li><strong>Стиль:</strong> Y2K / Tech-Runner / Gorpcore.</li><li><strong>Матеріали:</strong> синтетична сітка, преміальні полімерні накладки.</li></ul>',
    vendor: 'New Balance',
    productType: 'Взуття / Кросівки',
    tags: ['Кросівки', 'New Balance', 'Топ продажів', 'Gorpcore', 'Взуття', 'Y2K'],
    price: 6900,
    compareAtPrice: 7800,
    images: [
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'M1906REE',
    variants: [
      { id: 'v-nb-40', title: 'EU 40 (25.0 cm)', price: 6900, compareAtPrice: 7800, sku: 'M1906REE-40' },
      { id: 'v-nb-415', title: 'EU 41.5 (26.0 cm)', price: 6900, compareAtPrice: 7800, sku: 'M1906REE-415' },
      { id: 'v-nb-42', title: 'EU 42 (26.5 cm)', price: 6900, compareAtPrice: 7800, sku: 'M1906REE-42' },
      { id: 'v-nb-43', title: 'EU 43 (27.5 cm)', price: 6900, compareAtPrice: 7800, sku: 'M1906REE-43' },
      { id: 'v-nb-44', title: 'EU 44 (28.0 cm)', price: 6900, compareAtPrice: 7800, sku: 'M1906REE-44' },
      { id: 'v-nb-45', title: 'EU 45 (29.0 cm)', price: 6900, compareAtPrice: 7800, sku: 'M1906REE-45' },
    ],
  },
  {
    id: 'prod-carhartt-double-knee-pant',
    handle: 'carhartt-wip-double-knee-pant-hamilton-brown',
    title: "Carhartt WIP Double Knee Pant 'Hamilton Brown'",
    bodyHtml: '<p>Еталонні робочі штани з подвійними посиленими наколінниками та металевими заклепками. Виготовлені з надміцного фірмового органічного канвасу Dearborn Canvas, який набуває унікального вінтажного характеру з часом.</p><ul><li><strong>Матеріал:</strong> 100% органічна бавовна Dearborn Canvas (12 oz).</li><li><strong>Конструкція:</strong> потрійні посилені шви, утилітарні бічні кишені та петля для молотка.</li><li><strong>Крій:</strong> Relaxed straight fit з високою посадкою.</li></ul>',
    vendor: 'Carhartt WIP',
    productType: 'Одяг / Штани та джинси',
    tags: ['Штани', 'Carhartt WIP', 'Одяг', 'Workwear', 'Double Knee', 'Хіт'],
    price: 4800,
    compareAtPrice: 5600,
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'I029196-HZ',
    variants: [
      { id: 'v-car-30', title: 'W30 / L32', price: 4800, compareAtPrice: 5600, sku: 'I029196-HZ-30' },
      { id: 'v-car-32', title: 'W32 / L32', price: 4800, compareAtPrice: 5600, sku: 'I029196-HZ-32' },
      { id: 'v-car-34', title: 'W34 / L32', price: 4800, compareAtPrice: 5600, sku: 'I029196-HZ-34' },
      { id: 'v-car-36', title: 'W36 / L32', price: 4800, compareAtPrice: 5600, sku: 'I029196-HZ-36' },
    ],
  },
  {
    id: 'prod-salomon-xt6-black',
    handle: 'salomon-xt-6-black-phantom-ebony',
    title: "Salomon XT-6 'Black / Phantom'",
    bodyHtml: '<p>Легендарний трейловий силует, який став іконою gorpcore-стилю у світових столицях моди. Безшовна термополіуретанова конструкція Sensifit забезпечує неперевершену фіксацію та захист стопи в будь-яку погоду.</p><ul><li><strong>Шнурівка:</strong> надшвидка система затягування Quicklace з кишенею на язичку.</li><li><strong>Шасі:</strong> система Agile Chassis System (ACS) для стабільності на нерівній поверхні.</li><li><strong>Підошва:</strong> Mud Contagrip з агресивним протектором.</li></ul>',
    vendor: 'Salomon',
    productType: 'Взуття / Кросівки',
    tags: ['Кросівки', 'Salomon', 'Gorpcore', 'Quicklace', 'Взуття', 'Тренд'],
    price: 8200,
    compareAtPrice: 9400,
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'L41086600',
    variants: [
      { id: 'v-sal-41', title: 'EU 41 1/3 (26.0 cm)', price: 8200, compareAtPrice: 9400, sku: 'L41086600-41' },
      { id: 'v-sal-42', title: 'EU 42 (26.5 cm)', price: 8200, compareAtPrice: 9400, sku: 'L41086600-42' },
      { id: 'v-sal-425', title: 'EU 42 2/3 (27.0 cm)', price: 8200, compareAtPrice: 9400, sku: 'L41086600-425' },
      { id: 'v-sal-43', title: 'EU 43 1/3 (27.5 cm)', price: 8200, compareAtPrice: 9400, sku: 'L41086600-43' },
      { id: 'v-sal-44', title: 'EU 44 (28.0 cm)', price: 8200, compareAtPrice: 9400, sku: 'L41086600-44' },
      { id: 'v-sal-45', title: 'EU 45 1/3 (29.0 cm)', price: 8200, compareAtPrice: 9400, sku: 'L41086600-45' },
    ],
  },
  {
    id: 'prod-supreme-box-logo-crewneck',
    handle: 'supreme-box-logo-crewneck-heather-grey',
    title: "Supreme Box Logo Crewneck 'Heather Grey'",
    bodyHtml: '<p>Найбажаніший світшот у світі вуличної моди. Важкий щільний фліс Crossgrain Fleece канадського виробництва з вишитим червоним Box Logo на грудях. Обмежений реліз (limited drop).</p><ul><li><strong>Матеріал:</strong> 100% бавовна найвищої щільності (Heavyweight Crossgrain Fleece).</li><li><strong>Деталі:</strong> бічні ребристі вставки для свободи рухів, фірмові жакардові бірки.</li><li><strong>Походження:</strong> офіційний реліз Supreme New York.</li></ul>',
    vendor: 'Supreme',
    productType: 'Одяг / Худі та світшоти',
    tags: ['Світшот', 'Supreme', 'Одяг', 'Дроп', 'Box Logo', 'Deadstock'],
    price: 7500,
    compareAtPrice: 8900,
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'SUP-BOGO-GRY',
    variants: [
      { id: 'v-sup-m', title: 'M (Regular/Oversize)', price: 7500, compareAtPrice: 8900, sku: 'SUP-BOGO-M' },
      { id: 'v-sup-l', title: 'L (Regular/Oversize)', price: 7500, compareAtPrice: 8900, sku: 'SUP-BOGO-L' },
      { id: 'v-sup-xl', title: 'XL (Oversize)', price: 7500, compareAtPrice: 8900, sku: 'SUP-BOGO-XL' },
    ],
  },
  {
    id: 'prod-stone-island-soft-shell',
    handle: 'stone-island-soft-shell-r-jacket-black',
    title: "Stone Island Soft Shell-R Jacket 'Black'",
    bodyHtml: '<p>Високотехнологічна куртка з 2-шарової функціональної тканини Soft Shell-R з дихаючою мембраною та захистом від вітру й дощу (8000 мм водяного стовпа). Комплектується культовим знімним патчем Compass Badge на лівому рукаві.</p><ul><li><strong>Функціонал:</strong> вітрозахисна та водонепроникна мембрана, внутрішній шар з мікрофлісу.</li><li><strong>Фурнітура:</strong> двостороння блискавка YKK, регульований анатомічний капюшон.</li><li><strong>Автентичність:</strong> QR Certilogo для моментальної перевірки оригінальності.</li></ul>',
    vendor: 'Stone Island',
    productType: 'Одяг / Куртки та верхній одяг',
    tags: ['Куртки', 'Stone Island', 'Верхній одяг', 'Soft Shell', 'Badge', 'Преміум'],
    price: 17800,
    compareAtPrice: 21000,
    images: [
      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'SI-7715Q0122',
    variants: [
      { id: 'v-si-s', title: 'S (Slim/Regular)', price: 17800, compareAtPrice: 21000, sku: 'SI-7715Q0122-S' },
      { id: 'v-si-m', title: 'M (Regular)', price: 17800, compareAtPrice: 21000, sku: 'SI-7715Q0122-M' },
      { id: 'v-si-l', title: 'L (Regular)', price: 17800, compareAtPrice: 21000, sku: 'SI-7715Q0122-L' },
      { id: 'v-si-xl', title: 'XL (Regular)', price: 17800, compareAtPrice: 21000, sku: 'SI-7715Q0122-XL' },
    ],
  },
  {
    id: 'prod-stussy-8ball-tee-white',
    handle: 'stussy-8-ball-heavyweight-t-shirt-white',
    title: "Stüssy 8 Ball Heavyweight T-Shirt 'White'",
    bodyHtml: '<p>Культова футболка з легендарним графічним принтом 8 Ball на спині та мінімалістичним логотипом на грудях. Виготовлена з важкої попередньо випраної бавовни (Pre-shrunk cotton) для збереження ідеальної форми.</p><ul><li><strong>Склад:</strong> 100% важка бавовна (240 GSM).</li><li><strong>Крій:</strong> Boxy Oversize fit.</li><li><strong>Догляд:</strong> прання при 30°C навиворіт.</li></ul>',
    vendor: 'Stüssy',
    productType: 'Одяг / Футболки',
    tags: ['Футболки', 'Stüssy', 'Одяг', '8 Ball', 'Бавовна 100%', 'Хіт'],
    price: 2400,
    compareAtPrice: 2900,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'STU-8BALL-WHT',
    variants: [
      { id: 'v-8b-s', title: 'S (Boxy fit)', price: 2400, compareAtPrice: 2900, sku: 'STU-8BALL-S' },
      { id: 'v-8b-m', title: 'M (Boxy fit)', price: 2400, compareAtPrice: 2900, sku: 'STU-8BALL-M' },
      { id: 'v-8b-l', title: 'L (Boxy fit)', price: 2400, compareAtPrice: 2900, sku: 'STU-8BALL-L' },
      { id: 'v-8b-xl', title: 'XL (Boxy fit)', price: 2400, compareAtPrice: 2900, sku: 'STU-8BALL-XL' },
    ],
  },
  {
    id: 'prod-jacquemus-le-chiquito-moyen',
    handle: 'jacquemus-le-chiquito-moyen-leather-bag-black',
    title: "Jacquemus Le Chiquito Moyen Leather Bag 'Black'",
    bodyHtml: '<p>Культова дизайнерська сумка Le Chiquito Moyen від французького бренду Jacquemus. Виготовлена з гладкої преміальної шкіри з золотистим металевим логотипом JACQUEMUS. Комплектується знімним регульованим ременем через плече та фірмовим пильником.</p><ul><li><strong>Матеріал:</strong> 100% натуральна теляча шкіра, бавовняна підкладка.</li><li><strong>Деталі:</strong> магнітна застібка, золотиста фурнітура, фірмовий пильник Jacquemus у комплекті.</li><li><strong>Розміри:</strong> 18 x 13.5 x 8 см.</li></ul>',
    vendor: 'Jacquemus',
    productType: 'Сумки / Кросбоді',
    tags: ['Сумки', 'Jacquemus', 'Аксесуари', 'Шкіра', 'Преміум', 'Новинки'],
    price: 19800,
    compareAtPrice: 23500,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: '213BA002-3000-990',
    variants: [
      { id: 'v-jacq-os', title: 'One Size', price: 19800, compareAtPrice: 23500, sku: '213BA002-990-OS' },
    ],
  },
  {
    id: 'prod-ami-paris-ami-de-coeur-sweatshirt',
    handle: 'ami-paris-ami-de-coeur-organic-cotton-sweatshirt-noir',
    title: "AMI Paris Ami de Coeur Sweatshirt 'Noir / Red'",
    bodyHtml: '<p>Фірмовий світшот від паризького дому моди AMI Alexandre Mattiussi. Вишитий червоний символ любові та дружби Ami de Coeur на грудях та тональна вишивка AMI на спині. Щільна органічна французька бавовна French Terry.</p><ul><li><strong>Склад:</strong> 100% органічна бавовна (GOTS certified French Terry 420 GSM).</li><li><strong>Крій:</strong> Boxy regular fit. Зроблено в Португалії.</li><li><strong>Догляд:</strong> делікатне прання при 30°C.</li></ul>',
    vendor: 'AMI Paris',
    productType: 'Одяг / Худі та світшоти',
    tags: ['Світшот', 'AMI Paris', 'Одяг', 'Ami De Coeur', 'Органічна бавовна', 'Хіт'],
    price: 9200,
    compareAtPrice: 10800,
    images: [
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'BFUSW001-724-001',
    variants: [
      { id: 'v-ami-s', title: 'S (Regular fit)', price: 9200, compareAtPrice: 10800, sku: 'BFUSW001-S' },
      { id: 'v-ami-m', title: 'M (Regular fit)', price: 9200, compareAtPrice: 10800, sku: 'BFUSW001-M' },
      { id: 'v-ami-l', title: 'L (Regular fit)', price: 9200, compareAtPrice: 10800, sku: 'BFUSW001-L' },
      { id: 'v-ami-xl', title: 'XL (Regular fit)', price: 9200, compareAtPrice: 10800, sku: 'BFUSW001-XL' },
    ],
  },
  {
    id: 'prod-ganni-graphic-tee-white',
    handle: 'ganni-graphic-organic-cotton-t-shirt-white',
    title: "Ganni Graphic Organic Cotton T-Shirt 'Bright White'",
    bodyHtml: '<p>Культова футболка від копенгагенського бренду Ganni з фірмовим ретро-принтом та слоганом бренду. Створена з турботою про довкілля з 100% органічної сертифікованої бавовни.</p><ul><li><strong>Склад:</strong> 100% органічна бавовна.</li><li><strong>Крій:</strong> Вільний Scandinavian relaxed fit.</li><li><strong>Деталі:</strong> круглий виріз горловини в рубчик, стійкий шовкотрафаретний принт.</li></ul>',
    vendor: 'Ganni',
    productType: 'Одяг / Футболки',
    tags: ['Футболки', 'Ganni', 'Одяг', 'Скандинавський дизайн', 'Новинки'],
    price: 3600,
    compareAtPrice: 4200,
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'T3350-100',
    variants: [
      { id: 'v-gan-xs', title: 'XS (Relaxed)', price: 3600, compareAtPrice: 4200, sku: 'T3350-100-XS' },
      { id: 'v-gan-s', title: 'S (Relaxed)', price: 3600, compareAtPrice: 4200, sku: 'T3350-100-S' },
      { id: 'v-gan-m', title: 'M (Relaxed)', price: 3600, compareAtPrice: 4200, sku: 'T3350-100-M' },
      { id: 'v-gan-l', title: 'L (Relaxed)', price: 3600, compareAtPrice: 4200, sku: 'T3350-100-L' },
    ],
  },
  {
    id: 'prod-breda-jane-watch-gold',
    handle: 'breda-jane-vintage-gold-mesh-watch',
    title: "Breda Jane 1741 Gold Mesh Watch 'Champagne'",
    bodyHtml: '<p>Мінімалістичний вінтажний годинник від американського дизайн-ательє Breda (Даллас). Витончений овальний корпус із золотим PVD-покриттям, перламутровий циферблат та міланський сітчастий браслет.</p><ul><li><strong>Механізм:</strong> японський кварцовий Seiko / Miyota.</li><li><strong>Матеріал:</strong> нержавіюча сталь 316L з PVD-покриттям кольору 18K золота.</li><li><strong>Водонепроникність:</strong> 3 ATM (захист від бризок). Комплектується фірмовим футляром.</li></ul>',
    vendor: 'Breda',
    productType: 'Аксесуари / Годинники',
    tags: ['Аксесуари', 'Годинники', 'Breda', 'Jane', 'Подарунок', 'Преміум'],
    price: 6800,
    compareAtPrice: 7900,
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    available: true,
    sku: 'BREDA-1741-GLD',
    variants: [
      { id: 'v-breda-os', title: 'One Size (Регульований)', price: 6800, compareAtPrice: 7900, sku: 'BREDA-1741-GLD-OS' },
    ],
  },
];

export const SAMPLE_SHOPIFY_CSV = `Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Variant SKU,Variant Price,Variant Compare At Price,Image Src
air-jordan-1-lost-and-found,"Air Jordan 1 Retro High OG 'Chicago Lost & Found'","Культова класика 1985 року у вінтажному переосмисленні з натуральною шкірою.","Jordan","Взуття / Кросівки","Кросівки, Jordan, Хіт, Deadstock, Взуття",TRUE,"Title","EU 42 (26.5 cm)","DZ5485-612-42",9800,11500,https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800
jacquemus-le-chiquito-moyen,"Jacquemus Le Chiquito Moyen Leather Bag 'Black'","Культова дизайнерська сумка Le Chiquito Moyen з преміальної шкіри.","Jacquemus","Сумки / Кросбоді","Сумки, Jacquemus, Аксесуари, Шкіра, Преміум",TRUE,"Title","One Size","213BA002-990-OS",19800,23500,https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800
ami-paris-ami-de-coeur-sweatshirt,"AMI Paris Ami de Coeur Sweatshirt 'Noir / Red'","Фірмовий світшот з органічної бавовни French Terry з вишивкою Ami de Coeur.","AMI Paris","Одяг / Худі та світшоти","Світшот, AMI Paris, Одяг, Ami De Coeur, Хіт",TRUE,"Title","L (Regular fit)","BFUSW001-L",9200,10800,https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800
ganni-graphic-tee-white,"Ganni Graphic Organic Cotton T-Shirt 'Bright White'","Футболка зі 100% органічної бавовни з ретро-принтом у скандинавському стилі.","Ganni","Одяг / Футболки","Футболки, Ganni, Одяг, Скандинавський дизайн",TRUE,"Title","S (Relaxed)","T3350-100-S",3600,4200,https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800
breda-jane-watch-gold,"Breda Jane 1741 Gold Mesh Watch 'Champagne'","Мінімалістичний годинник з PVD-покриттям золота та міланським браслетом.","Breda","Аксесуари / Годинники","Аксесуари, Годинники, Breda, Преміум",TRUE,"Title","One Size","BREDA-1741-GLD-OS",6800,7900,https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800
stussy-basic-hoodie-black,"Stüssy Basic Applique Hoodie 'Black'","Фірмове важке худі з флісу щільністю 380 GSM від піонера каліфорнійського streetwear.","Stüssy","Одяг / Худі та світшоти","Худі, Stüssy, Одяг, Oversize, Хіт",TRUE,"Title","L (Oversize)","STU-HOOD-L",5400,6200,https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800
new-balance-1906r-silver,"New Balance 1906R 'Silver Metallic / Cordura'","Технологічний біговий силует початку 2000-х з амортизацією N-ergy та ABZORB.","New Balance","Взуття / Кросівки","Кросівки, New Balance, Топ продажів, Gorpcore",TRUE,"Title","EU 43 (27.5 cm)","M1906REE-43",6900,7800,https://images.unsplash.com/photo-1539185441755-769473a23570?w=800
carhartt-double-knee-pant,"Carhartt WIP Double Knee Pant 'Hamilton Brown'","Еталонні робочі штани з подвійними посиленими наколінниками та органічного канвасу.","Carhartt WIP","Одяг / Штани та джинси","Штани, Carhartt WIP, Одяг, Workwear",TRUE,"Title","W32 / L32","I029196-HZ-32",4800,5600,https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800
salomon-xt6-black,"Salomon XT-6 'Black / Phantom'","Культовий трейловий силует з системою швидкої шнурівки Quicklace та підошвою Contagrip.","Salomon","Взуття / Кросівки","Кросівки, Salomon, Gorpcore, Quicklace, Взуття",TRUE,"Title","EU 42.5 (27.0 cm)","L41086600-42",8200,9400,https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800
supreme-box-logo-crewneck,"Supreme Box Logo Crewneck 'Heather Grey'","Культовий світшот з вишитим червоним логотипом Box Logo з важкого флісу.","Supreme","Одяг / Худі та світшоти","Світшот, Supreme, Одяг, Дроп, Box Logo",TRUE,"Title","L (Regular)","SUP-BOGO-L",7500,8900,https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800
stone-island-soft-shell,"Stone Island Soft Shell-R Jacket 'Black'","Високотехнологічна куртка з мембраною Soft Shell-R та знімним патчем Compass Badge.","Stone Island","Одяг / Куртки та верхній одяг","Куртки, Stone Island, Верхній одяг, Soft Shell",TRUE,"Title","L (Regular)","SI-7715Q0122-L",17800,21000,https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800
stussy-8ball-tee-white,"Stüssy 8 Ball Heavyweight T-Shirt 'White'","Футболка з культовим принтом 8 Ball з важкої 100% бавовни щільністю 240 GSM.","Stüssy","Одяг / Футболки","Футболки, Stüssy, Одяг, 8 Ball, Бавовна 100%",TRUE,"Title","L (Boxy fit)","STU-8BALL-L",2400,2900,https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800
`;
